virtualenvfolder/bugmining/bugmining/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('mining_main/', include('mining_main.urls')),
    path('admin/', admin.site.urls),
]

virtualenvfolder/bugmining/mining_main/urls.py
from django.urls import path

from . import views

app_name = 'mining_main'
urlpatterns = [
    #ex: /miningmain
    path('', views.index, name='index'),

    #ex: /miningmain/5/
    #the 'name' value is called by the {%url} template tag
    path('<int:bug_id>/', views.bug_detail, name='bug_detail'),
    path('file/<int:file_id>/', views.file_detail, name='file_detail'),
    path('author/<int:author_id>/', views.author_detail, name='author_detail'),
    path('update-from-blog', views.update_bug_lists, name='updateblog'),
    path('update-from-git', views.get_metrics_from_git, name='updategit'),
    path('delete', views.delete_all_bugs, name='delete'),
    path('check-vuls', views.check_defects_in_next_release, name = 'checkvuls'),
    path('classifier', views.run_classifier, name = 'classifier'),

]

virtualenvfolder/bugmining/mining_main/models.py
from datetime import datetime

from django.db import models
from django.utils import timezone

class Bug(models.Model):
    bug_id = models.CharField(max_length=10)
    #to String
    def __str__(self):
        return self.bug_id

class Release(models.Model):
    release_number = models.CharField(max_length=200)
    #to String
    def __str__(self):
        return self.release_number

class File(models.Model):
    file_path =models.CharField(max_length=200)
    involved = models.IntegerField(default=0)
    total_changeset = models.IntegerField(default=0)
    bugs = models.ManyToManyField(Bug)
    release = models.ForeignKey(Release, on_delete=models.CASCADE)
    added = models.IntegerField(default=0)
    deleted = models.IntegerField(default=0)
    #to String
    def __str__(self):
        return self.file_path

class Author(models.Model):
    author_name = models.CharField(max_length=200)
    files = models.ManyToManyField(File)
    def __str__(self):
        return self.author_name

virtualenvfolder/bugmining/mining_main/forms.py
from django import forms

class ReleaseForm(forms.Form):
    release_number = forms.CharField(label='Release Number', max_length=100)

class ClassifierForm(forms.Form):
    release_number = forms.CharField(label='Release Number', max_length=100)
    metrics = forms.CharField(label='Metrics', max_length=100)

virtualenvfolder/bugmining/mining_main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from .models import Bug, File, Author, Release
from .bug_id_scraping import get_bugids, get_gerrit_links
from .js_scraping import get_inner_html, get_committed_files, get_authors, get_date
from .code_metrics_scraping import get_code_metrics, get_release, check_vulnerability, get_occurrences
from .classifier import classifier_defect, classifier_defect_fold
from .forms import ReleaseForm
from django.http import HttpResponseRedirect

PATH = 0
ADDED = 1
DELETED = 2
CHANGESET = 3
BUGS = 4

def index(request):
    """
    Handle index page request
    """
    file_list = File.objects.order_by('-added')[:5]
    template = loader.get_template('mining_main/index.html')
    context = {
        'file_list' : file_list
    }
    return render(request, 'mining_main/index.html', context)

def bug_detail(request, bug_id):
    """
    Handle bug page request
    """
    bug = get_object_or_404(Bug, pk=bug_id)
    return render(request, 'mining_main/bug_detail.html', {'bug': bug})

def file_detail(request, file_id):
    """
    Handle file page request
    """
    file = get_object_or_404(File, pk=file_id)
    return render(request, 'mining_main/file_detail.html', {'file': file})

def author_detail(request, author_id):
    """
    Handle author page request
    """
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'mining_main/author_detail.html', {'author': author})


def update_author_database(author_name, file):
    try:
        author = Author.objects.get(author_name=author_name)
        # author.files.add(file)
    except Author.DoesNotExist:
        author = Author(author_name=author_name)
        author.save()
        # author.files.add()
    author.files.add(file)
    author.save()
    return author

def update_bug_lists(request):
    """
    Scrape all data of all bugs from the Bug Blog
    Limit: 6000 bugs
    """
    ids = get_bugids()
    ids.sort()
    ids.reverse()
    top5 = ids[:100]
    i = 0
    for id in top5:
        try:
            b = Bug.objects.get(bug_id=str(id))
        except Bug.DoesNotExist:
            b = Bug(bug_id=str(id))
            b.save()
            get_info_from_bug(b)
            i += 1
            print("finished ", i, " bugs")
    file_list = File.objects.order_by('-involved')[:10]
    template = loader.get_template('mining_main/index.html')
    context = {
        'file_list' : file_list
    }
    return render(request, 'mining_main/index.html', context)

def delete_all_bugs(request):
    """
    Delete all data from the database
    """
    Release.objests.all().delete()
    Author.objects.all().delete()
    return index(request)

def get_info_from_blog(bug):
    """
    Scrape data of the given bug from the Bug blog
    """
    url = "https://bugs.chromium.org/p/chromium/issues/detail?id=" + bug.bug_id
    links = get_gerrit_links(url)
    if links is not None:
        for link in links:
            innerhtml = get_inner_html(link)
            files = get_committed_files(innerhtml)
            author_name = get_authors(innerhtml)
            date = get_date(innerhtml)
            if files is not None:
                for file_info in files:
                    f = update_file_from_blog(file_info, bug, len(files))
                    a = update_author_database(author_name,f)

def update_file_from_blog(file_info, bug, changeset):
    """
    Update data of the bug from the blog to the database
    """
    path = file_info[PATH]
    added = file_info[ADDED]
    deleted = file_info[DELETED]
    try:
        f = File.objects.get(file_path=path)

    except File.DoesNotExist:
        f = File(file_path=path)
        f.save()
    f.added += int(added)
    f.deleted += int(deleted)
    f.last_updated = bug.updated_date
    f.total_changeset += changeset
    try:
        b = f.bugs.get(bug)
    except Bug.DoesNotExist:
        f.bugs.add(bug)
        f.involved += 1
    f.save()
    return f

def get_metrics_from_git(request):
    """
    Scrape file metrics data from the given release changelog url
    Metrics collected: ADDED, DELETED, CHANGSET
    """
    if request.method == 'POST':
        form = ReleaseForm(request.POST)
        if form.is_valid():
            release_number = request.POST.get("release_number")
            url = "https://chromium.googlesource.com/chromium/src/+log/" + release_number + "?pretty=fuller&n=10000"
            release_number = get_release(url)
            print("Release number: ", release_number)
            try:
                release = Release.objects.get(release_number=release_number)
            except Release.DoesNotExist:
                release = Release(release_number=release_number)
                release.save()
                path_metrics_changeset_bugs = get_code_metrics(url)
                for file_info in path_metrics_changeset_bugs:
                    update_files_from_git(file_info, release)
            return HttpResponseRedirect('/mining_main/')
        else:
            form = ReleaseForm()
            return HttpResponseRedirect('/mining_main/')

def update_files_from_git(file_info, release):
    """
    Update collected data from a release changelog to the database
    """
    path = file_info[PATH]
    added = file_info[ADDED]
    deleted = file_info[DELETED]
    changeset = file_info[CHANGESET]
    bugids = file_info[BUGS]
    bugs = []
    for bugid in bugids:
        try:
            bug = Bug.objects.get(bug_id=str(bugid))
        except Bug.DoesNotExist:
            bug = Bug(bug_id=str(bugid))
            bug.save()
            print("added ", bugid)
        bugs.append(bug)

    try:
        f = File.objects.get(file_path=path, release=release)
    except File.DoesNotExist:
        f = File(file_path=path, release=release)
        f.save()
        print("added ", f.file_path)
    f.added += int(added)
    f.deleted += int(deleted)
    f.total_changeset += int(changeset)-1
    for bug in bugs:
        try:
            b = f.bugs.get(bug_id=bug.bug_id)
        except Bug.DoesNotExist:
            f.bugs.add(bug)
            f.involved += 1
    f.save()
    return f

def check_defects_in_next_release(request):
    """
    Connect to the change log of the latest release for the list of defect files
    Find the files in the database that are defective
    """
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ReleaseForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            release_number = request.POST.get("release_number")
            # release_number = "65.0.3325.181..66.0.3359.117"
            files_list = File.objects.all()
            file_path_list = set()
            for file in files_list:
                file_path_list.add(file.file_path)

            # url = "https://chromium.googlesource.com/chromium/src/+log/66.0.3359.181..67.0.3396.62?pretty=fuller&n=10000"
            url = "https://chromium.googlesource.com/chromium/src/+log/" + release_number + "?pretty=fuller&n=10000"
            next_release_defects = check_vulnerability(url)
            files_defects_map = map_files_and_bugs(file_path_list, next_release_defects)
        else:
            form = ReleaseForm()
            return HttpResponseRedirect('/mining_main/')

    # url_occ = "https://chromium.googlesource.com/chromium/src/+log/65.0.3325.181..66.0.3359.117?pretty=fuller&n=500"
    # files_occs = get_occurrences(file_path_list, url_occ)
    # # data_set = collect_data_set(files_defects_map)
    # for file_occ in files_occs:
    #     file = File.objects.get(file_path=file_occ[0], release__release_number=release_number)
    #     file.involved = file_occ[1]
    #     file.save()

    template = loader.get_template('mining_main/result.html')
    context = {
        'files_defects_map' : files_defects_map
    }
    return render(request, 'mining_main/result.html', context)

def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/mining_main/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'mining_main/name.html', {'form': form})

def map_files_and_bugs(file_path_list, next_release_defects):
    """
    From the list of defective file of the latest release, mark all files in
    the database if they are defective
    """
    bugs_in_files = []
    counter = 0
    defect_counter = 0
    for file in file_path_list:
        is_defect = 0
        if file in next_release_defects:
            is_defect = 1
            defect_counter += 1
        bugs_in_files.append(is_defect)
        counter += 1
        print("Checked ", counter, "/", len(file_path_list))
    print("Defect: ", defect_counter, "/", len(file_path_list))
    files_defects_map = zip(file_path_list, bugs_in_files)
    return files_defects_map



def print_defect_status(files_defects_map):
    defect_list = open("defect.txt", "w")
    non_defect_list = open("non-defect.txt", "w")
    is_defect = 0
    not_defect = 0
    for file_defect_status in files_defects_map:
        print(file_defect_status[0], ": ", file_defect_status[1])
        if(file_defect_status[1]):
            defect_list.write(file_defect_status[0] + "\n")
            is_defect += 1
        else:

virtualenvfolder/bugmining/mining_main/templates/mining_main/author_detail.html
<h1>{{ author.name}}</h1>
Files edited:
<ul>
{% for file in author.files.all %}
    <li><a href="{% url 'mining_main:file_detail' file.id%}">{{ file.file_path }}</a></li>
{% endfor %}
</ul>

virtualenvfolder/bugmining/mining_main/templates/mining_main/bug_detail.html
<h1>Bug ID: {{ bug.bug_id }}</h1>
<ul>
{% for file in bug.file_set.all %}
    <li><a href="{% url 'mining_main:file_detail' file.id%}">{{ file.file_path }} {{file.involved}}</a></li>
{% endfor %}
</ul>

virtualenvfolder/bugmining/mining_main/templates/mining_main/classifier.html
<style type="text/css">
#container {
  height: 70%;
  width: 100%;
  display: flex;
}
#leftBlock {
  width: 50%;
  background-color: white;
}

#rightBlock {
  width: 50%;
  background-color: white;
}
</style>

{% if metrics_used %}
<p>Metrics used in Classifier:<br></p>
<br>
  {% for metric in metrics_used %}
    <font color="red"> <i>{{metric}}</i></font><br>
  {% endfor%}
{% else %}
  <p>No metrics are available.</p>
<br>
{% endif %}
<div id="container">


  <div id="leftBlock">
    {% if binary_classification %}
    <br>
    <table border="1">
      <tr>
          <th width = "20%"></th>
          <th width = "20%">Recall</th>
          <th width = "20%">False alarm</th>
          <th width = "20%">Precision</th>
          <th width = "20%">F1</th>
      </tr>
      {% for result in binary_classification %}
      <tr>
          <td></td>
          <td align = "center">{{ result.0 }}</td>
          <td align = "center">{{ result.1 }}</td>
          <td align = "center">{{ result.2 }}</td>
          <td align = "center">{{ result.3 }}</td>
      </tr>
      {% endfor%}
      {% if average_binary_classification %}
      <tr bgcolor = "#ADD8E6">
        <td align = "center">Average</td>
        <td align = "center">{{ average_binary_classification.0 }}</td>
        <td align = "center">{{ average_binary_classification.1 }}</td>
        <td align = "center">{{ average_binary_classification.2 }}</td>
        <td align = "center">{{ average_binary_classification.3 }}</td>
      </tr>
      {% else %}
        <p>No results are available.</p>
      {% endif %}

    </table>
    {% else %}
        <p>No results are available.</p>
    {% endif %}
  </div>

  <div id="rightBlock">
    {% if positive_negative %}
    <br>
    <table border="1">
      <tr>
          <th width = "50"></th>
          <th width = "50">  TP  </th>
          <th width = "50">  TN  </th>
          <th width = "50">  FP  </th>
          <th width = "50">  FN  </th>
      </tr>
      {% for item in positive_negative %}
      <tr>
          <td></td>
          <td align = "center">{{ item.0 }}</td>
          <td align = "center">{{ item.1 }}</td>
          <td align = "center">{{ item.2 }}</td>
          <td align = "center">{{ item.3 }}</td>
      </tr>
      {% endfor%}
      {% if average_positive_negative %}
      <tr bgcolor = "#ADD8E6">
        <td align = "center">Average</td>
        <td align = "center">{{ average_positive_negative.0 }}</td>
        <td align = "center">{{ average_positive_negative.1 }}</td>
        <td align = "center">{{ average_positive_negative.2 }}</td>
        <td align = "center">{{ average_positive_negative.3 }}</td>
      </tr>
      {% else %}
        <p>No results are available.</p>
      {% endif %}
    </table>
    {% else %}
        <p>No results are available.</p>
    {% endif %}
  </div>

</div>
<a href="{% url 'mining_main:index' %}">Home</a>

virtualenvfolder/bugmining/mining_main/templates/mining_main/file_detail.html
<h1>{{ file.file_path}}</h1>
<ul>
    Added: {{file.added}} <br>
    Deleted: {{file.deleted}} <br>
    Involved count: {{file.involved}} <br>
    ChangeSet: {{file.total_changeset}} <br>
    Last updated: {{file.last_updated}} <br>
</ul>
Bugs appeared in:
<ul>
{% for bug in file.bugs.all %}
    <li><a href="{% url 'mining_main:bug_detail' bug.id%}">{{ bug.bug_id }}</a></li>
{% endfor %}
</ul>
Authors edited:
<ul>
{% for author in file.author_set.all %}
    <li><a href="{% url 'mining_main:author_detail' author.id%}">{{ author.author_name }}</a></li>
{% endfor %}
</ul>

virtualenvfolder/bugmining/mining_main/templates/mining_main/index.html
<p>Classifier Guide: <br>
<br>
Enter Release Changelog in the form of <b>[Previous Release]..[Next Release]</b> <br>
e.g: <b>66.0.3359.181..67.0.3396.62</b> <br>
<br>
Enter metrics in the form of <b>[metric 1], [metrics 2], [metric 3]</b> <br>
e.g: <b>1,2,3</b>, where <br>
</p>
<ul>
    <li> 0 = Number of lines ADDED </li>
    <li> 1 = Number of lines DELETED </li>
    <li> 2 = Average of lines ADDED </li>
    <li> 3 = Average of lines DELETED </li>
    <li> 4 = Average of CHANGESET </li>
</ul>

<form action="{% url 'mining_main:updategit' %}" method="post">
    {% csrf_token %}
    <label for="release_number">Release changelog: </label>
    <input id="release_number" type="text" name="release_number" value="{{ current_release_number }}">
    <input type="submit" value="Update database">
</form>

<form action="{% url 'mining_main:checkvuls' %}" method="post">
    {% csrf_token %}
    <label for="release_number">Release changelog: </label>
    <input id="release_number" type="text" name="release_number" value="{{ current_release_number }}">
    <input type="submit" value="Check Vulnerabilities">
</form>

<form action="{% url 'mining_main:classifier' %}" method="post">
    {% csrf_token %}
    <label for="release_number">Release changelog: </label>
    <input id="release_number" type="text" name="release_number" value="{{ current_release_number }}">
    <label for="metrics">Metrics to use: </label>
    <input id="metrics" type="text" name="metrics" value="{{ current_metrics }}">
    <input type="submit" value="Run Classifier">
</form>

virtualenvfolder/bugmining/mining_main/templates/mining_main/result.html
{% if files_defects_map %}
<table>
    {% for file in files_defects_map %}
    <tr>
        <td>{{ file.0}}</td>
        <td>{{ file.1}}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
    <p>No files are available.</p>
{% endif %}

<a href="{% url 'mining_main:index' %}">Home</a>